
"""
utils.py
========
General utility helpers shared across the application:

* BMI calculation
* PDF report export (using fpdf2)
* Simple fairness analysis across demographic groups
"""

from __future__ import annotations

import io
import logging
from datetime import datetime

import numpy as np
import pandas as pd
from fpdf import FPDF

from config import LOG_FORMAT, LOG_LEVEL

logging.basicConfig(level=LOG_LEVEL, format=LOG_FORMAT)
logger = logging.getLogger(__name__)


# --------------------------------------------------------------------------
# BASIC HELPERS
# --------------------------------------------------------------------------
def calculate_bmi(weight_kg: float, height_cm: float) -> float:
    """Calculate Body Mass Index (BMI) from weight (kg) and height (cm).

    Args:
        weight_kg: Body weight in kilograms.
        height_cm: Height in centimetres.

    Returns:
        BMI rounded to 1 decimal place. Returns 0.0 if height is invalid.
    """
    if height_cm <= 0:
        return 0.0
    height_m = height_cm / 100.0
    return round(weight_kg / (height_m ** 2), 1)


# --------------------------------------------------------------------------
# PDF REPORT GENERATION
# --------------------------------------------------------------------------
class DiabetesReportPDF(FPDF):
    """Custom FPDF subclass adding a consistent header/footer."""

    def header(self) -> None:  # noqa: D102 (fpdf hook)
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 30, 30)
        self.cell(0, 10, "Diabetes Risk Screening Report", ln=True, align="C")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Generated by the Explainable AI Diabetes Risk System", ln=True, align="C")
        self.ln(4)

    def footer(self) -> None:  # noqa: D102 (fpdf hook)
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def generate_pdf_report(
    patient: dict,
    risk_band: str,
    risk_score: float,
    confidence: float,
    reasoning_trace: list[str],
    recommendations: list[str],
) -> bytes:
    """Generate a PDF risk-screening report and return it as raw bytes.

    Args:
        patient: Raw patient input values.
        risk_band: Predicted risk category (e.g. "High Risk").
        risk_score: Risk probability, expressed as a percentage (0-100).
        confidence: Model confidence score (0-100).
        reasoning_trace: List of human-readable reasoning steps.
        recommendations: List of lifestyle/medical recommendations.

    Returns:
        The PDF file content as a ``bytes`` object, ready to be offered as
        a Streamlit download.
    """
    pdf = DiabetesReportPDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Prediction Summary", ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 7, f"Risk Category: {risk_band}", ln=True)
    pdf.cell(0, 7, f"Risk Score: {risk_score:.1f}%", ln=True)
    pdf.cell(0, 7, f"Model Confidence: {confidence:.1f}%", ln=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Patient Inputs", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for key, value in patient.items():
        pdf.cell(0, 6, f"{key}: {value}", ln=True)
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Reasoning Trace", ln=True)
    pdf.set_font("Helvetica", "", 9)
    if reasoning_trace:
        for step in reasoning_trace:
            pdf.multi_cell(0, 5.5, f"- {step}")
    else:
        pdf.multi_cell(0, 5.5, "No additional symbolic rules fired for this patient.")
    pdf.ln(3)

    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(0, 8, "Recommendations", ln=True)
    pdf.set_font("Helvetica", "", 10)
    for rec in recommendations:
        pdf.multi_cell(0, 6, f"- {rec}")
    pdf.ln(4)

    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(150, 0, 0)
    pdf.multi_cell(
        0,
        5,
        "Disclaimer: This report is generated by an automated screening tool "
        "for educational purposes only. It is NOT a medical diagnosis. "
        "Please consult a licensed healthcare professional for an accurate "
        "diagnosis and treatment plan.",
    )

    output = pdf.output(dest="S")
    if isinstance(output, str):
        return output.encode("latin-1")
    return bytes(output)


# --------------------------------------------------------------------------
# FAIRNESS ANALYSIS
# --------------------------------------------------------------------------
def fairness_by_group(df: pd.DataFrame, group_col: str, prediction_col: str = "Outcome") -> pd.DataFrame:
    """Compute simple fairness statistics (positive-prediction rate) across
    the groups of a demographic column.

    Args:
        df: DataFrame containing at least ``group_col`` and
            ``prediction_col``.
        group_col: Column defining the demographic groups (e.g. "Gender").
        prediction_col: Binary outcome/prediction column (1 = positive).

    Returns:
        A DataFrame with, per group: count, positive rate (%), and mean
        risk score, useful for spotting disparate impact.
    """
    grouped = (
        df.groupby(group_col)[prediction_col]
        .agg(["count", "mean"])
        .rename(columns={"count": "Count", "mean": "PositiveRate"})
    )
    grouped["PositiveRate"] = (grouped["PositiveRate"] * 100).round(2)
    return grouped.reset_index()


def age_group_bucket(age: float) -> str:
    """Bucket a numeric age into a coarse age-group label for fairness
    analysis."""
    if age < 30:
        return "18-29"
    if age < 45:
        return "30-44"
    if age < 60:
        return "45-59"
    return "60+"
